export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAILURE = "STAFF_LOGIN_FAILURE";
export const CLEAR_STAFF_LOGIN = 'CLEAR_STAFF_LOGIN';

export const STAFF_LOGOUT_SUCCESS = "STAFF_LOGOUT_SUCCESS";
export const STAFF_LOGOUT_FAILURE = "ADD_JOB_STEPS_FAILURE";

export const USER_LISTING_SUCCESS = 'USER_LISTING_SUCCESS';
export const USER_LISTING_FAILURE = 'USER_LISTING_FAILURE';

export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';
export const CLEAR_OTP = 'CLEAR_OTP';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
export const CLEAR_GET_USER_PROFILE = 'CLEAR_GET_USER_PROFILE';

