export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAILURE = "STAFF_LOGIN_FAILURE";

export const STAFF_LOGOUT_SUCCESS = "STAFF_LOGOUT_SUCCESS";
export const STAFF_LOGOUT_FAILURE = "ADD_JOB_STEPS_FAILURE";

